### ISSUE TITLE
您好，关于demo和test_net的问题

### ISSUE THREAD

**Issue by dragonhaha** [hustvl/SparseInst#10]
您好，感谢您和您的团队的excellent work。在使用demo.py进行可视化的时候我遇到了点问题
这行你们貌似漏了结束时间。
https://github.com/hustvl/SparseInst/blob/98dc323103e34f5253e19ba28cc6d4da290417d3/demo.py#L104

还有，在我是用自己的COCO格式数据集遇到了这个问题
[04/06 08:53:36 fvcore.common.checkpoint]: [Checkpointer] Loading from output/sparse_inst_r50_giam_aug/model_0014999.pth ...
  0% 0/960 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/content/drive/MyDrive/colab/SparseInst/detectron2/detectron2/utils/visualizer.py:409: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  masks = np.asarray(predictions.pred_masks)
/content/drive/MyDrive/colab/SparseInst/detectron2/detectron2/utils/visualizer.py:409: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  masks = np.asarray(predictions.pred_masks)
  0% 0/960 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 95, in <module>
    img, args.confidence_threshold)
  File "/content/drive/MyDrive/colab/SparseInst/sparseinst/d2_predictor.py", line 67, in run_on_image
    predictions=instances)
  File "/content/drive/MyDrive/colab/SparseInst/detectron2/detectron2/utils/visualizer.py", line 410, in draw_instance_predictions
    masks = [GenericMask(x, self.output.height, self.output.width) for x in masks]
  File "/content/drive/MyDrive/colab/SparseInst/detectron2/detectron2/utils/visualizer.py", line 410, in <listcomp>
    masks = [GenericMask(x, self.output.height, self.output.width) for x in masks]
  File "/content/drive/MyDrive/colab/SparseInst/detectron2/detectron2/utils/visualizer.py", line 103, in __init__
    raise ValueError("GenericMask cannot handle object {} of type '{}'".format(m, type(m)))
ValueError: GenericMask cannot handle object tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]]) of type '<class 'torch.Tensor'>'

请问该如何解决呢？
我使用的环境是colab。安装detectron的方式如下
!git clone https://github.com/facebookresearch/detectron2.git
!pip install -U scipy
!pip install omegaconf==2.1.* pyyaml>=5.1
!python setup.py build develop

还有一个问题是，训练过程没有问题，并且训练过程中的评估也没有问题。
但是使用test_net.py时一直卡在这里，不知道和上一个问题有没有什么关联。
[04/06 09:09:09 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(512, 512), max_size=853, sample_style='choice')]
[04/06 09:09:09 d2.data.common]: Serializing 959 elements to byte tensors and concatenating them all ...
[04/06 09:09:09 d2.data.common]: Serialized dataset takes 0.55 MiB
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
/usr/local/lib/python3.7/dist-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/usr/local/lib/python3.7/dist-packages/numpy/core/fromnumeric.py:3441: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.7/dist-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
process: [0/959] fps: nan

非常感谢！

**Comment by wondervictor** [comment]
Thanks for reminding me!
As for the problem in `demo.py`, it might be the problem caused by the versions.
You may modify the `detectron2/utils/visualizer.py` Line 402:
https://github.com/facebookresearch/detectron2/blob/221448e4dcfbebf215b8d21ae7e4b1dfbf422d29/detectron2/utils/visualizer.py#L402

by adding `tensor` to `predictions.pred_masks.tensor`. Since we (and detectron2)  adopt `BitMasks` to store the predicted binary masks. It might be a solution for this problem. As for the `test_net.py`, it's not a bug. You have 959 samples to evaluate and the logging period is 1000, you can reduce the period in Line 156. The scripts is running for AP evaluation, which takes a little time.

**Comment by dragonhaha** [comment]
Thanks for your reply~   I modified visualizer.py as you said and it worked successfully.

**Comment by dragonhaha** [comment]
> Thanks for reminding me! As for the problem in `demo.py`, it might be the problem caused by the versions. You may modify the `detectron2/utils/visualizer.py` Line 402: https://github.com/facebookresearch/detectron2/blob/221448e4dcfbebf215b8d21ae7e4b1dfbf422d29/detectron2/utils/visualizer.py#L402 by adding `tensor` to `predictions.pred_masks.tensor`. Since we (and detectron2) adopt `BitMasks` to store the predicted binary masks. It might be a solution for this problem. As for the `test_net.py`, it's not a bug. You have 959 samples to evaluate and the logging period is 1000, you can reduce the period in Line 156. The scripts is running for AP evaluation, which takes a little time.



> Thanks for reminding me! As for the problem in `demo.py`, it might be the problem caused by the versions. You may modify the `detectron2/utils/visualizer.py` Line 402: https://github.com/facebookresearch/detectron2/blob/221448e4dcfbebf215b8d21ae7e4b1dfbf422d29/detectron2/utils/visualizer.py#L402 by adding `tensor` to `predictions.pred_masks.tensor`. Since we (and detectron2) adopt `BitMasks` to store the predicted binary masks. It might be a solution for this problem. As for the `test_net.py`, it's not a bug. You have 959 samples to evaluate and the logging period is 1000, you can reduce the period in Line 156. The scripts is running for AP evaluation, which takes a little time.

Thanks for your reply~ I modified visualizer.py as you said and it worked successfully.
