### ISSUE TITLE
inference speed on video

### ISSUE THREAD

**Issue by mrfsc** [hustvl/SparseInst#11]
Hi, the inference speed has not reached the ideal level, only less than 3FPS when the model runs on my custom video with one 
 1080ti GPU. Is there a problem with my parameter settings?

Here is my shell command and results:
**python demo.py  --config-file configs/sparse_inst_r50_giam.yaml --video-input  cars.mp4 --output results/output.mp4 --opt MODEL.WEIGHTS sparse_inst_r50_giam_aug_2b7d68.pth INPUT.MAX_SIZE_TEST 640**

[04/07 19:45:01 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/sparse_inst_r50_giam.yaml', input=None, opts=['MODEL.WEIGHTS', 'sparse_inst_r50_giam_aug_2b7d68.pth', 'INPUT.MAX_SIZE_TEST', '640'], output='results/output.mp4', video_input='cars.mp4', webcam=False)
[04/07 19:45:03 fvcore.common.checkpoint]: [Checkpointer] Loading from sparse_inst_r50_giam_aug_2b7d68.pth ...
  0%|                                                                                                 | 0/266 [00:00<?, ?it/s]/home/user/InstanceSeg/detectron2/detectron2/structures/image_list.py:114: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  max_size = (max_size + (stride - 1)) // stride * stride
/home/user/anaconda3/envs/seg/lib/python3.7/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
100%|███████████████████████████████████████████████████████████████████████████████████████| 266/266 [01:44<00:00,  2.55it/s]

**Comment by wondervictor** [comment]
Hi @mrfsc, the inference speeds of `demo` CAN NOT reflect the actual speed of SparseInst. The inference speed  of `demo` is much slower, because:
(1) the visualization of masks is much slower,
(2) writing and loading video frames
(3) detectron2 supports associating adjacent frames for better visualizations.
For pure inference speed, we suggest using `test_net.py` to evaluate, while the `demo.py` takes much time for visualizations.

**Comment by wondervictor** [comment]
In addition, we have a plan to optimize and simplify the visualization process.

**Comment by mrfsc** [comment]
Thanks, used **test_net.py** to evaluate my custom data formatted as coco 2017 and got the ideal excellent inference speed. 
Looking forward to your update.

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟  or help us recommend SparseInst to your friends.

**Comment by MolianWH** [comment]
@wondervictor 
Hi! Thanks for your greate work. I test the demo and test_net.py, the speed record bellow:

**GPU Mem Use**：1274Mb
**Test Env**:  1080Ti
**Input size**：640×360
**fps**:
<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

operation | fps
-- | --
normal visualization | 7fps
remove detectron2 vis | 22fps
remove video frame load, save and display( only run self.predictor(frame)) | 26fps
test_net.py (run same video frame data with above)| 37.62fps

</div>

You see the last 2 rows not equal, what I think they should be same or similar. What's the reason? 
One the other hand, if I run a larger pixel video(1080*1920), demo normal vis speed is down to 2fps.

By the way, could you provide a video infer demo with high speed?
