### ISSUE TITLE
onnx export inference caused Nan value while in pytorch normal

### ISSUE THREAD

**Issue by jinfagang** [hustvl/SparseInst#14]
Hi, I exported sparsinst to onnx. It can gen onnx, and when export, I printed out the values of scores, it was normal, but when inference using onnxruntime, caused Nan values.

I know it should not related with model itself, but I want ask ,which part may caused this problem? It shouldn't happen since onnx trace is very mature now.

**Comment by jinfagang** [comment]
Solved it.

**Comment by wondervictor** [comment]
Hi @jinfagang, thanks for your interest in SparseInst.
Could you share your solutions to exporting SparseInst to ONNX?
We're continuing to develop this framework including ONNX and TensorRT while the limited time affects the overall progress. We will appreciate it much if you can share your code about ONNX export through a hopeful pull request!

**Comment by jinfagang** [comment]
@wondervictor Hi, I merged sparsinst into [YOLOv7](https://github.com/jinfagang/yolov7) which also a framework based on detectron2, I made export onnx in it. 
I will also provide int8 quantization support (both for CPU and TensorRT) later.

**Comment by wondervictor** [comment]
Hi @jinfagang, we'd love to add a link to YOLOv7, which is awesome work!

**Comment by jinfagang** [comment]
@wondervictor thanks. I will also PR to you for some quantized sparseinst onnx model why I finished this part.

**Comment by wondervictor** [comment]
We've done it and will release the ONNX models soon.

**Comment by LukasMahieuArinti** [comment]
Hi @wondervictor, any updates on when you'll be releasing the onnx conversion code? Thank you kindly.

**Comment by wondervictor** [comment]
Hi @LukasMahieuArinti, ONNX now is supported and we update the scripts for ONNX converson.
