### ISSUE TITLE
RepVGG backbone supported

### ISSUE THREAD

**Issue by ForestWang** [hustvl/SparseInst#15]
would you like to add RepVGG as backbone, which is GPU friendly.

**Comment by wondervictor** [comment]
Thanks for your advice and we'd like to support these efficient architectures in the near future!

**Comment by wondervictor** [comment]
Hi @ForestWang, we'd like to notify you about this feature or update as soon as we finish it. We believe it will take a short time for us to finish it. This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 .
