### ISSUE TITLE
mask AP with better backbone

### ISSUE THREAD

**Issue by LiWentomng** [hustvl/SparseInst#2]
Thanks for your great work.

The speed reported in your paper is great.  It seems that it can also achieve the great mask AP performance with better backbone, e.g. R-101, R101-DCN, or Swin-transformer.  Will your provide the better mask AP performance based on more better bakbones?    There exits "MLP" , is it a pure and fully convolutional  framework ?

**Comment by wondervictor** [comment]
Hi, thanks for your interest in SparseInst!
Yeah, we will provide more models with different backbones, including both convolutional networks, e.g., ResNet-101, and vision transformers, e.g., Swin Transformer and PVT. We are preparing and training now, please stay tuned!☕️
The `MLP` in the decoder contains a fully connected layer (linear) with a ReLU, along with three linear layers for classification, objectness, and mask kernel. After extracting features through attention maps, we apply linear layers to obtain the recognition and segmentation results.

**Comment by LiWentomng** [comment]
Thanks for your reply!  I  see~    Looking  forward to the SparseInst models of  with high AP performance.

**Comment by wondervictor** [comment]
Thank you much! We will add more models as soon as possible. If you have any other questions, please feel free to raise an issue 👏.
