### ISSUE TITLE
The instance object could not be detected

### ISSUE THREAD

**Issue by KengDong** [hustvl/SparseInst#20]
python demo.py --config-file configs/sparse_inst_r50_giam.yaml --input val2017/* --output results --opt MODEL.WEIGHTS sparse_inst_r50_giam_aug_2b7d68.pth INPUT.MIN_SIZE_TEST 64

[04/29 09:56:48 detectron2]: val2017/000000000139.jpg: detected 0 instances in 0.29s
  0%|                                                                                                                                                                                         | 1/5000 [00:00<31:45,  2.62it/s][04/29 09:56:49 detectron2]: val2017/000000000285.jpg: detected 0 instances in 0.18s
  0%|                                                                                                                                                                                         | 2/5000 [00:00<26:48,  3.11it/s][04/29 09:56:49 detectron2]: val2017/000000000632.jpg: detected 0 instances in 0.03s
  0%|                                                                                                                                                                                         | 3/5000 [00:00<19:08,  4.35it/s][04/29 09:56:49 detectron2]: val2017/000000000724.jpg: detected 0 instances in 0.09s
  0%|▏                                                                                                                                                                                        | 4/5000 [00:00<16:38,  5.01it/s][04/29 09:56:49 detectron2]: val2017/000000000776.jpg: detected 0 instances in 0.03s
[04/29 09:56:49 detectron2]: val2017/000000000785.jpg: detected 0 instances in 0.02s
  0%|▏                                                                                                                                                                                        | 6/5000 [00:01<11:58,  6.95it/s][04/29 09:56:49 detectron2]: val2017/000000000802.jpg: detected 0 instances in 0.02s
  0%|▎                                                                                                                                                                                        | 7/5000 [00:01<11:03,  7.53it/s]

**Comment by wondervictor** [comment]
Hi @KengDong, thanks for your interest in SparseInst.
You adopt the `64` as the `MIN_SIZE_TEST`, which is extremely small. You might increase the input size to `512` or `640`.

**Comment by KengDong** [comment]
/home/lu/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/utils/visualizer.py:402: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  masks = np.asarray(predictions.pred_masks)
/home/lu/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/utils/visualizer.py:402: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  masks = np.asarray(predictions.pred_masks)
  0%|                                                                                                                                                                                                 | 0/5000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demo.py", line 96, in <module>
    img, args.confidence_threshold)
  File "/home/lu/code/SparseInst-main/sparseinst/d2_predictor.py", line 69, in run_on_image
    predictions=instances)
  File "/home/lu/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/utils/visualizer.py", line 403, in draw_instance_predictions
    masks = [GenericMask(x, self.output.height, self.output.width) for x in masks]
  File "/home/lu/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/utils/visualizer.py", line 403, in <listcomp>
    masks = [GenericMask(x, self.output.height, self.output.width) for x in masks]
  File "/home/lu/anaconda3/envs/py37/lib/python3.7/site-packages/detectron2/utils/visualizer.py", line 96, in __init__
    raise ValueError("GenericMask cannot handle object {} of type '{}'".format(m, type(m)))
ValueError: GenericMask cannot handle object tensor([[False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        ...,
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False],
        [False, False, False,  ..., False, False, False]]) of type '<class 'torch.Tensor'>'

**Comment by KengDong** [comment]
After I changed min_ SIZE_ For a problem after test, I have also experimented with other PTH models, all of which have errors or are unable to detect instance objects.

**Comment by KengDong** [comment]
Thank you for your answer. I'll light a star for you first

**Comment by wondervictor** [comment]
Thanks for your support and interest in SparseInst 😊 .  We have fixed the problem in the latest commit. This issue will be closed, you can open a new issue if you have other problems or reopen it.
