### ISSUE TITLE
demo speed without visualization and video save is low 

### ISSUE THREAD

**Issue by MolianWH** [hustvl/SparseInst#27]
Thanks for your greate work. I reference [issue #11](https://github.com/hustvl/SparseInst/issues/11#issuecomment-1092409408) and test the demo and test_net.py, the speed record bellow:

**GPU Mem Use**：1274Mb
**Test Env**:  1080Ti
**Input size**：640×360
**fps**:
<div class="okr-block-clipboard" data-okr="%7B%22okrDelta%22%3A%5B%7B%22lineType%22%3A%22unsupport%22%2C%22lineOptions%22%3A%7B%7D%2C%22lineContent%22%3A%5B%5D%7D%5D%2C%22businessKey%22%3A%22lark-doc%22%7D"></div><div data-zone-id="0" data-line-index="0" style="white-space: pre;">

operation | fps
-- | --
normal visualization | 7fps
remove detectron2 vis | 22fps
remove video frame load, save and display( only run self.predictor(frame)) | 26fps
test_net.py (run same video frame data with above)| 37.62fps

</div>

You see the last 2 rows not equal, what I think they should be same or similar. What's the reason? 
One the other hand, if I run a larger pixel video(1080*1920), demo normal vis speed is down to 2fps.

By the way, could you provide a video infer demo with high speed?

**Comment by wondervictor** [comment]
Hi @MolianWH, thanks for your interest in SparseInst!
This problem is interesting, and the difference exists because the `demo`, as well as the `predictor`, consist of massive preprocessing and post-processing steps even if you only obtain the speed of the `predictor(frame)`. The `test_net.py` can measure the accurate speed since it's simple without extra procedures but the evaluation.  Besides, we suggest you use `torch.cuda.synchronize` and `time.perf_counter` to measure the exact time instead of the progress bar. If you are stuck on this problem, you can provide more details about it, e.g., the code, and we'd like to help you solve it.

**Comment by fabro66** [comment]
我通过对比[sparseinst.py](https://github.com/hustvl/SparseInst/blob/c3f122c3fe2fbc7a58a38045c8b7627c81680676/sparseinst/sparseinst.py#L114)（demo.py调用）和[test_net.py](https://github.com/hustvl/SparseInst/blob/c3f122c3fe2fbc7a58a38045c8b7627c81680676/test_net.py#L82)中的SparseInst推理代码，发现推理逻辑的顺序不一样。
`sparseinst.py`中pred_scores的计算是所有预测实例都进行，而在`test_net.py`中只有预测类别保留下的才计算scores，这会造成推理结果和推理速度都有区别。

- sparseinst.py
``` python
    def inference(self, output, batched_inputs, max_shape, image_sizes):
        # max_detections = self.max_detections
        results = []
        pred_scores = output["pred_logits"].sigmoid()
        pred_masks = output["pred_masks"].sigmoid()
        pred_objectness = output["pred_scores"].sigmoid()
        pred_scores = torch.sqrt(pred_scores * pred_objectness)
    
        for _, (scores_per_image, mask_pred_per_image, batched_input, img_shape) in enumerate(zip(
                pred_scores, pred_masks, batched_inputs, image_sizes)):

            ori_shape = (batched_input["height"], batched_input["width"])
            result = Instances(ori_shape)
            # max/argmax
            scores, labels = scores_per_image.max(dim=-1)
            # cls threshold
            keep = scores > self.cls_threshold
            scores = scores[keep]
            labels = labels[keep]
            mask_pred_per_image = mask_pred_per_image[keep]

            if scores.size(0) == 0:
                result.scores = scores
                result.pred_classes = labels
                results.append(result)
                continue

            h, w = img_shape
            # rescoring mask using maskness
            scores = rescoring_mask(scores, mask_pred_per_image > self.mask_threshold, mask_pred_per_image)
```

- test_net.py
```python
    def inference_single(self, outputs, img_shape, pad_shape, ori_shape):
        """
        inference for only one sample
        Args:
            scores (tensor): [NxC]
            masks (tensor): [NxHxW]
            img_shape (list): (h1, w1), image after resized
            pad_shape (list): (h2, w2), padded resized image
            ori_shape (list): (h3, w3), original shape h3*w3 < h1*w1 < h2*w2
        """
        result = Instances(ori_shape)
        # scoring
        pred_logits = outputs["pred_logits"][0].sigmoid()
        pred_scores = outputs["pred_scores"][0].sigmoid().squeeze()
        pred_masks = outputs["pred_masks"][0].sigmoid()
        # obtain scores
        scores, labels = pred_logits.max(dim=-1)
        # remove by thresholding
        keep = scores > self.cls_threshold
        scores = torch.sqrt(scores[keep] * pred_scores[keep])
        labels = labels[keep]
        pred_masks = pred_masks[keep]

        if scores.size(0) == 0:
            return None
        scores = rescoring_mask(scores, pred_masks > 0.45, pred_masks)
```

**Comment by wondervictor** [comment]
Hi @fabro66, thanks for your interest in SparseInst!
The difference about the `keep = scores > self.cls_threshold` between `train_net.py` and `test_net.py`

**Comment by wondervictor** [comment]
In addition, using `test_net.py` and `train_net.py` as well as `demo.py` can obtain the same evaluation results.

**Comment by wondervictor** [comment]
We believe we have answered your question, and as such I'm closing this issue, but let us know if you have further questions. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
