### ISSUE TITLE
Can you provide a training log of one SparseInst model?

### ISSUE THREAD

**Issue by liujiaheng** [hustvl/SparseInst#30]
This is an excellent paper, and I am trying to implement SparseInst on another dataset. 
Thus, I am wondering to verify whether the training losses decreased in the right way.

Thanks.
Jiaheng.

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
