### ISSUE TITLE
Slow Execution on 1650 Ti

### ISSUE THREAD

**Issue by andrearosasco** [hustvl/SparseInst#33]
I know that I won't be able to reach full performances on my hardware but when I run this simple demo script

```python
# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
import copy
import multiprocessing as mp
import time
import cv2
import numpy as np
from detectron2.config import get_cfg
from detectron2.engine import DefaultPredictor
from detectron2.utils.logger import setup_logger
from sparseinst import VisualizationDemo, add_sparse_inst_config


# constants
WINDOW_NAME = "COCO detections"


def draw_mask(rgb, mask):
    overlay = copy.deepcopy(rgb)
    if np.any(mask):
        overlay[mask] = np.array([0, 0, 128])
    return cv2.addWeighted(rgb, 1, overlay, 0.5, 0)

if __name__ == "__main__":
    mp.set_start_method("spawn", force=True)

    setup_logger(name="fvcore")
    logger = setup_logger()

    cfg = get_cfg()
    add_sparse_inst_config(cfg)
    cfg.merge_from_file('configs/sparse_inst_r50vd_dcn_giam_aug.yaml')
    cfg.merge_from_list(['MODEL.WEIGHTS', 'checkpoints/sparse_inst_r50vd_dcn_giam_aug_67dc06.pth'])
    # Set score_threshold for builtin models
    cfg.MODEL.RETINANET.SCORE_THRESH_TEST = 0.5
    cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
    cfg.MODEL.PANOPTIC_FPN.COMBINE.INSTANCES_CONFIDENCE_THRESH = 0.5
    cfg.freeze()

    demo = VisualizationDemo(cfg)

    camera = cv2.VideoCapture(0)
    model = DefaultPredictor(cfg)

    while True:
        _, rgb = camera.read()
        rgb = cv2.cvtColor(rgb, cv2.COLOR_BGR2RGB)

        start = time.perf_counter()
        predictions = model(rgb)
        print(1 / (time.perf_counter() - start))

        predictions = predictions["instances"]
        predictions = predictions[predictions.scores > 0.5].to('cpu')

        rgb = cv2.cvtColor(rgb, cv2.COLOR_RGB2BGR)
        res = draw_mask(rgb, predictions.pred_masks.numpy()[0])
        cv2.imshow('', res)
        cv2.waitKey(1)
```
 the speed is around 8fps. Is there any configuration tuning that I can do to improve performances? Also, is the speed of the model suppose to degrade with the number of instances?

Anyway, thanks for the great work!

**Comment by wondervictor** [comment]
Hi @andrearosasco, thanks for your interest in SparseInst! Firstly, how about the input size of your input image? It seems that you adopt the frames from the camera, which may produce high-resolution images, e.g., 1920×1080 for an HD camera, and slows the inference speed. The inference speed of SparseInst is measured on one 2080 Ti with 640(608)x864 input size.  In addition, reducing the number of instances will increase the inference speed, but not significantly.

**Comment by andrearosasco** [comment]
Hey @wondervictor! In my case the input images read through opencv are 640x480x3 (I think it's opencv default behavior since I didn't set any flag). I guess I'll have to get my hands on a better GPU then.

**Comment by wondervictor** [comment]
Could you run the `test_net.py` for inference speed, which measures the actual speed of the model. If the actual inference speed by `test_net.py` is about 8 fps, the slow execution may attribute to the device.

**Comment by wondervictor** [comment]
We believe we have answered your question, and as such I'm closing this issue, but let us know if you have further questions. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
