### ISSUE TITLE
Cant download the model from google driver

### ISSUE THREAD

**Issue by wuqiangch** [hustvl/SparseInst#4]
Cant download the model from google driver.Could you  share the model on baidu pan please?

**Comment by wondervictor** [comment]
Hi, @wuqiangch, we will upload these models on BaiduPan as soon as possible.

**Comment by wuqiangch** [comment]
Ok，Thanks.

**Comment by wondervictor** [comment]
Hi @wuqiangch, we have uploaded the weights on BaiduPan, you can download all weights from this [link](https://pan.baidu.com/s/1tot7Wcoi4J1xh8ZS7VikZg)(password:lkdo).
