### ISSUE TITLE
inference speed is toooo low

### ISSUE THREAD

**Issue by WXLL579** [hustvl/SparseInst#40]
demo.py , speed of this file is very slow
if test_net.py, how to test videos???

**Comment by Willforcv** [comment]
how about fps with gpu?

**Comment by WXLL579** [comment]
did not compute. 
but a 10s video need more than 2min to inference
![image](https://user-images.githubusercontent.com/82254264/173731025-ebdb4f64-bf4a-4cb0-a97d-d9a66c3fede7.png)

**Comment by wondervictor** [comment]
Hi @WXLL579 @Willforcv, thanks for your interest in SparseInst.
Using `demo.py` to infer on videos requires much time for drawing masks and associating masks between frames, which are implemented by detectron2. The pure inference without visualizations is fast. You may refer to the previous issue https://github.com/hustvl/SparseInst/issues/11. For pure inference time, you might run the `test_net.py` to measure the model speed.
We'd like to simplify the visualization procedures for faster visualization but we don't have enough time recently.

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
