### ISSUE TITLE
Convert "pth" file to "pkl"

### ISSUE THREAD

**Issue by BryantGary** [hustvl/SparseInst#45]
Hello, I failed to use pretrained model recently. Do you have a useful script for converting "pth" file downloaded from pytorch to "pkl"?

**Comment by wondervictor** [comment]
Hi @BryantGary, thanks for your interest in SparseInst.
Does the pre-trained model here mean to the backbone network, e.g., ResNet?

**Comment by wondervictor** [comment]
We believe we have answered your question, and as such I'm closing this issue, but let us know if you have further questions. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
