### ISSUE TITLE
Checkpointer loader issue

### ISSUE THREAD

**Issue by charming2992** [hustvl/SparseInst#46]
[06/29 16:22:29 fvcore.common.checkpoint]: [Checkpointer] Loading from output/sparse_inst_r50vd_dcn_giam_aug/model_0004999.pth ...
  0%|                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]/home/wangshuo/miniconda3/envs/dec/lib/python3.8/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)

**Comment by wondervictor** [comment]
Hi @charming2992, thanks for your interest in SparseInst.
You need to download the models from the model zoo in the README.  And the below warning can be ignored since it doesn't affect the training/testing.

**Comment by charming2992** [comment]
> Hi @charming2992, thanks for your interest in SparseInst. You need to download the models from the model zoo in the README. And the below warning can be ignored since it doesn't affect the training/testing.

I loaded the model(0004999.pth) I have trained on my own data. And I tested by train_net.py and test_net.py, all perform well. But it perform bad by demo.py. You have said the bug in demo.py( BGR format) in other issue. I fixed the input format bug, it still gets bad performance. Maybe it caused by the checkpointer loading?

**Comment by wondervictor** [comment]
Hi @charming2992, I think it's an unknown bug that leads to bad visualization results. I'm diving into it to solve it. Stay tuned!

**Comment by wondervictor** [comment]
We believe we have answered your question, and as such I'm closing this issue, but let us know if you have further questions. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
