### ISSUE TITLE
Replaced with self-made COCO format data set training error

### ISSUE THREAD

**Issue by Rain-yal** [hustvl/SparseInst#47]
Hi, I am a newbie. I'm having trouble training my own COCO format dataset, can you help me? Thank you.
![sendpix0](https://user-images.githubusercontent.com/46081613/176680626-896880eb-651a-4887-a559-0f9f583440ce.jpg)

**Comment by wondervictor** [comment]
Hi @Rain-yal, thanks for your interest in SparseInst.
It seems that this problem is due to the number of categories. You need to change the `NUM_CLASSES` in the decoder to 11 to adapt to your dataset.

**Comment by wondervictor** [comment]
We believe we have answered your question, and as such I'm closing this issue, but let us know if you have further questions. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
