### ISSUE TITLE
inference my data

### ISSUE THREAD

**Issue by miaomiaoge** [hustvl/SparseInst#5]
How to predict mask about my own data

**Comment by wondervictor** [comment]
Hi @miaomiaoge,
(1) if you want to obtain the evaluation results, e.g., on your own data, you could convert your own data into COCO format and then evaluate using `train_net.py`.
(2) if you prefer the visualization results on your images, you might run the `demo`, which will be updated within two days.

**Comment by miaomiaoge** [comment]
thank you very much

**Comment by wondervictor** [comment]
Hi @miaomiaoge, we've updated the code and provided the demo.py to infer your own images and obtain the visualization results. Please check [Visualizing Images with SparseInst](https://github.com/hustvl/SparseInst/blob/main/README.md#visualizing-images-with-sparseinst)

**Comment by wondervictor** [comment]
We believe we have answered your question, and as such I'm closing this issue, but let us know if you have further questions.
