### ISSUE TITLE
Huge AP drop when I change image size

### ISSUE THREAD

**Issue by Jtao0818** [hustvl/SparseInst#50]
I use default settings to train on my custom data and everything is OK.
For fair comparison, I try to replace the augments as commonly used in other projects and re-train the model. But this leads to ~10 AP drop and it's quite unreasonable. I also tried to remove the CROP augment but it didn't work. So I wonder whether I have omitted something.
The main changes in my configs are as follow.
`INPUT:
  MAX_SIZE_TEST: 1333
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MIN_SIZE_TRAIN_SAMPLING: choice`
 Do you have some idea about this issue?

**Comment by wondervictor** [comment]
Hi @Jtao0818, have you solved this problem? Sorry for the late reply : (

**Comment by chiayuhsu** [comment]
Hi @Jtao0818, did you find out why? I have the same issue on my custom data as well. Thanks!
