### ISSUE TITLE
visualization problm

### ISSUE THREAD

**Issue by qiumeng6** [hustvl/SparseInst#51]
Hello！
Thanks for your work！
The IAM is very cool and we will quote it in our paper,
but we have some problem about visualization of Instance activiation map.
Could you give me some advice!

**Comment by wondervictor** [comment]
Hi @qiumeng6, thanks for your recognition and interest in SparseInst!

**Comment by qiumeng6** [comment]
Yes，we don‘t konw how to visualize instance activation maps 
and we try to use CAM but it does not work.

**Comment by wondervictor** [comment]
To visualize the instance activation maps, you only need to save/visualize the `pred_iam` by turning on `cfg.MODEL.SPARSE_INST.DECODER.OUTPUT_IAM`. The decoder will output the instance activation maps in the by `output['pred_iam']`. You can obtain the instance activation maps in the inference stage.

**Comment by qiumeng6** [comment]
OK ！
Thank you！
