### ISSUE TITLE
How to export to ONNX?

### ISSUE THREAD

**Issue by sarmientoj24** [hustvl/SparseInst#52]
Any instructions for exporting it to onnx?

**Comment by wondervictor** [comment]
You can follow the [PyTorch official guide](https://pytorch.org/docs/stable/onnx.html) to export SparseInst to an ONNX model or wait a minute for me to update.
During the conversion, you might meet the following problems:
1. Fix the input size to `640x640`.
2. `AdaptiveAvgPool` is not supported in ONNX operations: you can use `AvgPool` with predefined kernel size and stride to replace the `AdaptiveAvgPool`.
2. `Sigmoid + Normalize` may incur NaN or conversion problem, you can remove the `clamp` or increase the `eps`.
These problems have been solved but I need to sparse some time to update the code.

**Comment by wondervictor** [comment]
Hi @sarmientoj24, ONNX now is supported.

**Comment by wondervictor** [comment]
We believe we have answered your question, and as such I'm closing this issue, but let us know if you have further questions. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
