### ISSUE TITLE
如何指定分割的物体类别？

### ISSUE THREAD

**Issue by JXFOnestep** [hustvl/SparseInst#54]

**Comment by wondervictor** [comment]
SparseInst will output `pred_logits` and `pred_masks`. The `pred_logits` is a `NxC` tensor (C=80 for COCO, denotes the categories). You can obtain the categories by argmax `pred_logits` and find/index the corresponding category through COCO annotations.

**Comment by JXFOnestep** [comment]
Thank you! I got it
