### ISSUE TITLE
How to freeze layers in backbone

### ISSUE THREAD

**Issue by TeodorChiaburu** [hustvl/SparseInst#59]
Hello!

Can someone please explain how we can freeze the backbone or part of it? I see the parameter `FREEZE_AT` in the configs (like in the link below), but I did not manage to understand what values it can take. In some files it is 0, in others it is 2...

https://github.com/hustvl/SparseInst/blob/8e75c646233822ee751253c799eb58226eb5f577/configs/Base-SparseInst.yaml#L7

Thank you!

**Comment by wondervictor** [comment]
Hi @TeodorChiaburu, thanks for your interest in SparseInst.
Freezing some stages of the backbone is a trick for finetuning. Take ResNet for example, `FREEZE_AT=1` will freeze the layers in the stem network and `FREEZE_AT=2` will freeze the layers in the stem network and stage 1 network. While `FREEZE_AT=0` means no freezing. You can check more details in `detectron2/modeling/backbone/resnet.py:L457`

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.

**Comment by 116022017144** [comment]
> Hi @TeodorChiaburu, thanks for your interest in SparseInst. Freezing some stages of the backbone is a trick for finetuning. Take ResNet for example, `FREEZE_AT=1` will freeze the layers in the stem network and `FREEZE_AT=2` will freeze the layers in the stem network and stage 1 network. While `FREEZE_AT=0` means no freezing. You can check more details in `detectron2/modeling/backbone/resnet.py:L457`

Hello, If I want to freezezn the all of backbone, then I set FREEZE_AT=5, right?
