### ISSUE TITLE
Train result on custom data

### ISSUE THREAD

**Issue by Tungway1990** [hustvl/SparseInst#6]
Hi, thanks for your great work. 

I have tried to use your code in custom data (about 20k training and 4k val, 13 classes) and compare with Mask RCNN on 1 single GPU card (RTX 2070 super)

Results are below:
1. Mask RCNN (iter: 200k, batch size: 4, pre_train model: mask_rcnn_R_50_FPN_3x.yaml)

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.403
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.631
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.437
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.112
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.275
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.533
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.366
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.457
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.458
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.151
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.345
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.577
[04/03 15:58:30 d2.evaluation.coco_evaluation]: Evaluation results for segm: 
|   AP   |  AP50  |  AP75  |  APs   |  APm   |  APl   |
|:------:|:-------:|:--------:|:------:|:--------:|:------:|
| 40.312 | 63.136 | 43.687 | 11.243 | 27.500 | 53.349 |

[04/03 15:58:30 d2.evaluation.coco_evaluation]: Per-category segm AP: 
| category      | AP     | category       | AP     | category     | AP     |
|:--------------|:-------|:---------------|:-------|:-------------|:-------|
| Category1    | 51.541 | Category2   | 29.145 | Category3 | 35.621 |
| Category4    | 24.693 | Category5   | 58.366 | Category6 | 53.629 |
| Category7    | 51.605 | Category8   | 43.764 |Category9  | 42.385 |
| Category10  | 23.205 | Category11 | 52.592 | Category12| 15.845|
| Category13  | 41.662 |                     |            |                   |             |

2. SparseInst (iter: 200k, batch size: 4, pre_train model: sparse_inst_r50vd_dcn_giam_aug.yaml)

 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.385
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.600
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.405
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.072
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.214
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.546
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.362
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.439
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.440
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.113
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.287
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.593
[04/04 04:18:07 d2.evaluation.coco_evaluation]: Evaluation results for segm: 
|   AP   |  AP50  |  AP75  |  APs  |  APm   |  APl   |
|:------:|:--------:|:-------:|:-----:|:------:|:------:|
| 38.494 | 59.989 | 40.544 | 7.178 | 21.401 | 54.632 |

[04/04 04:18:07 d2.evaluation.coco_evaluation]: Per-category segm AP: 
| category      | AP     | category       | AP     | category     | AP     |
|:--------------|:-------|:---------------|:-------|:-------------|:-------|
| Category1    | 44.075 | Category2  | 30.420 | Category3 | 18.588 |
| Category4    | 23.403 | Category5  | 49.850 | Category6 | 50.509 |
| Category7    | 52.993 | Category8  | 40.491 | Category9 | 43.866 |
| Category10  | 42.439 | Category11| 50.337 | Category12| 16.078 |
| Category13  | 37.367 |                    |            |                    |            |

Seems SparseInst have lower accuracy compare with Mask RCNN on similar iter and batch size, though the inference speed is much faster. I notice that SparsInst has slow convergence speed in https://github.com/hustvl/SparseInst/issues/1. Would you advice to increase the batch size to increase the performance?

And, error occured when cfg.SOLVER.AMP.ENABLED is set to True. Will SparseInst support fp16 in the future?

Thanks.

**Comment by wondervictor** [comment]
Hi @Tungway1990, thanks for your interest in SparseInst!
Exactly, SparseInst requires longer epochs for training than Mask R-CNN due to the convergence, and we are working on it now for the faster convergence speed. We'd like to share with you if we make any progress. For your problem, you might increase the batch size or training epochs during training. SparseInst with a longer schedule can significantly achieve better performance, whch is proved in the MS-COCO dataset. If you have other problems, please feel free to raise them!
As for FP16 or mix precision, we are moving the code into a higher version of detectron2, i.e., v0.6. Sure, this is a key feature and will be supported in the near future.

**Comment by wondervictor** [comment]
Hi @Tungway1990, you're right! The rescoring will lower the confidence of the predictions.
We adopt two different rescoring methods, i.e., IoU-objectness, and the other one is based on the raw mask predictions, which is mentioned above. We hope the confidence score can be more consistent with the actual quality of the mask predictions.

**Comment by Tungway1990** [comment]
Ooops, seem I overlook there are two rescoring method. 

` def rescoring_mask` is not referring IoU-objectness?

**Comment by wondervictor** [comment]
Yep, rescoring using `IoU-objectness` is simple, and is implemented using `torch.sqrt(pred_scores * pred_objectness)`.

**Comment by Tungway1990** [comment]
Got it, thanks

**Comment by wondervictor** [comment]
Hi @Tungway1990, SparseInst now supports FP16, which saves much memory and improve the training/inference speed.
