### ISSUE TITLE
Augmentation during training

### ISSUE THREAD

**Issue by TeodorChiaburu** [hustvl/SparseInst#61]
Hello!
I would like to apply some augmentation for training the SparseInst. I see there is an option to activate transformations such as `CROP`, `COLOR_JITTER` or `RANDOM_FLIP` under the feature `INPUT` in the config file. However, I could not find any evidence in the logs that these augmentation techniques were indeed applied during training. From the logs I could only read:

`Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(200, 200), max_size=853, sample_style='choice')]`

Am I missing something? Thank you for your great work!

**Comment by wondervictor** [comment]
Hi @TeodorChiaburu, the log you put here is about `inference`, while for training, the log will tell you what augmentations. Maybe this is a bug in the logger of the custom `dataset_mapper` in SparseInst, which doesn't log the augmentations in training. I'll fix it as soon as possible. However, you can print it directly by adding a `print` in 
https://github.com/hustvl/SparseInst/blob/main/sparseinst/dataset_mapper.py#L91
Hope it can help you.

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
