### ISSUE TITLE
Multiple checkpoints during training

### ISSUE THREAD

**Issue by TeodorChiaburu** [hustvl/SparseInst#62]
Is there a way to save the current state of the model multiple times during training? Right now only the final model at the end of the whole training is being saved. I see there is an attribute `CHECKPOINT_PERIOD` under `SOLVER` in the config file and tried changing it, but - as expected - it had no impact on the checkpoint frequency of the model weights.

**Comment by wondervictor** [comment]
Hi @TeodorChiaburu,  thanks for your interest in SparseInst!
By default, `detectron2` will save the checkpoint every 5000 iterations. You can change it by setting `SOLVER.CHECKPOINT_PERIOD` to the number you prefer. Or you can add an option in the training script as follows:
```bash
python train_net.py --config-file <path/to/config> --num-gpus 8 SOLVER.CHECKPOINT_PERIOD 1000
```
