### ISSUE TITLE
怎样得到flops和params

### ISSUE THREAD

**Issue by dhagsdjsb** [hustvl/SparseInst#63]

**Comment by wondervictor** [comment]
Hi @dhagsdjsb, we've updated and added a script to compute the FLOPs and parameters for SparseInst, you can try it now.

**Comment by dhagsdjsb** [comment]
谢谢您们。




------------------&nbsp;Original message&nbsp;------------------
From: "Tianheng Cheng"; 
Sendtime: Tuesday, Aug 9, 2022 5:23 PM
To: "hustvl/SparseInst"; 
Cc: "信息202001  ***@***.***>; "Mention"; 
Subject: Re: [hustvl/SparseInst] 怎样得到flops和params (Issue #63)





 
Hi @dhagsdjsb, we've updated and added a script to compute the FLOPs and parameters for SparseInst, you can try it now.

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.

**Comment by dhagsdjsb** [comment]
已给，也已强烈安利。




------------------&nbsp;Original message&nbsp;------------------
From: "Tianheng Cheng"; 
Sendtime: Tuesday, Aug 9, 2022 5:26 PM
To: "hustvl/SparseInst"; 
Cc: "信息202001  ***@***.***>; "Mention"; 
Subject: Re: [hustvl/SparseInst] 怎样得到flops和params (Issue #63)





 
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
