### ISSUE TITLE
KeyError: 'segmentation' 

### ISSUE THREAD

**Issue by sarmientoj24** [hustvl/SparseInst#65]
I am getting this error.

```
  File "/home/SparseInst/sparseinst/dataset_mapper.py", line 153, in __call__
    instances = utils.annotations_to_instances(
  File "/home/SparseInst/detectron2/detectron2/data/detection_utils.py", line 400, in annotations_to_instances
    segms = [obj["segmentation"] for obj in annos]
  File "/home/SparseInst/detectron2/detectron2/data/detection_utils.py", line 400, in <listcomp>
    segms = [obj["segmentation"] for obj in annos]
KeyError: 'segmentation'
```

It seems that `segmentation` is `None` but the `bbox` is there when I tried printing the output  
https://github.com/facebookresearch/detectron2/blob/9921a2caa585d4fa66c4b534b6fab6e74d89b582/detectron2/data/detection_utils.py#L400

I re-checked my annotations and it seems like the number of `bbox` and `segmentation` are equal which means all `bbox` have `segmentation`

**Comment by wondervictor** [comment]
Hi @sarmientoj24, this error might raise when there is no segmentation mask, which may have been removed. With data augmentation such as random crop, we suggest you use `polygon` instead of `bitmasks` as the `mask_format`. Using random crop with `bitmasks` tends to produce some empty mask.

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends?
