### ISSUE TITLE
How do you use the backbone models and load them as well?

### ISSUE THREAD

**Issue by sarmientoj24** [hustvl/SparseInst#67]
Or are they backbone weights already included when `cfg.MODEL.WEIGHTS` are loaded?

**Comment by wondervictor** [comment]
Hi @sarmientoj24, each config file provides a pretrained model, which will be loaded at the begin of the training.

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
