### ISSUE TITLE
How can I get pred_mask?

### ISSUE THREAD

**Issue by xiaona123456** [hustvl/SparseInst#7]
Hello, how can I get the pred_mask, I am looking forward to your reply.

**Comment by wondervictor** [comment]
Hi @xiaona123456, we will provide the scripts of `inference` and `visualization` today.

**Comment by wondervictor** [comment]
Hi @xiaona123456, we've updated the code and provided the `demo.py` to infer your own images and obtain the visualization results. Please check [Visualizing Images with SparseInst](https://github.com/hustvl/SparseInst/blob/main/README.md#visualizing-images-with-sparseinst)

**Comment by wondervictor** [comment]
We believe we have answered your question, and as such I'm closing this issue, but let us know if you have further questions.

**Comment by xiaona123456** [comment]
Thank you for your excellent work and you have solved my problem, thank u
