### ISSUE TITLE
No penalty for unmatched prediction

### ISSUE THREAD

**Issue by zoucheng1991** [hustvl/SparseInst#77]
In the criterion module, there seems to be no penalty for unmatched prediction, the loss is only computed with matched pred and gt.
the result is during the test, there will be multiple detections for a single object, thus NMS is needed.

Do you intentionally skip the penalty for unmatched predictions or you did it somewhere else in the code?

thx!

**Comment by wondervictor** [comment]
Hi @zoucheng1991, the penalty for unmatched predictions is from the classification loss, which consists of both positive (matched) predictions and negative (unmatched) predictions. The classification probability is helpful to remove the duplicate predictions. You may find that duplcate masks tend to have low confidence scores.

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
