### ISSUE TITLE
How to make the output image into a binary image？

### ISSUE THREAD

**Issue by BibibNanana** [hustvl/SparseInst#85]
I want my output to be a binary image, how do I do that？？Like this:
**
![image](https://user-images.githubusercontent.com/39188004/194025531-fac49767-a2fd-4fc3-a8a1-c2435d3921e6.png)
**

**Comment by wondervictor** [comment]
Hi @BibibNanana, thanks for your interest in SparseInst!
Maybe, you can convert your images from RGB to L (grayscale) images and then apply thresholding to obtain the binary images.

**Comment by BibibNanana** [comment]
> Hi @BibibNanana, thanks for your interest in SparseInst! Maybe, you can convert your images from RGB to L (grayscale) images and then apply thresholding to obtain the binary images.

Thank you for your reply, I've already done that

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends?
