### ISSUE TITLE
Setting thresholds during inference

### ISSUE THREAD

**Issue by neo031995** [hustvl/SparseInst#86]
Can someone explan the difference between 

`cfg.MODEL.SPARSE_INST.CLS_THRESHOLD 
`
and 

`cfg.MODEL.SPARSE_INST.MASK_THRESHOLD `

during inference?. I assume CLS_THRESHOLD is for the class probabilities. But how would changing MASK_THRESHOLD affect the inference?

**Comment by wondervictor** [comment]
Hi @neo031995, thanks for your interest in SparseInst!
* `CLS_THRESHOLD` aims for filtering instances whose `scores` are below the threshold.
* `MASK_THRESHOLD` is the threshold for converting probability masks into binary masks.

**Comment by neo031995** [comment]
Excuse me if it is silly asking again. So,
`CLS_THRESHOLD` will eliminate all the predicted instances     whose rescored probability score is less than the threshold.
`MASK_THRESHOLD` will eliminate all the predicted masks on those instances whose value is less than the threshold?

**Comment by wondervictor** [comment]
`MASK_THRESHOLD ` determines the positive/negative areas of the predicted masks, it filters negative pixels but does not filter the instances.

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it. Thanks for your interest in SparseInst 😊 . If you find it useful in your work or research, could you give us a star 🌟 or help us recommend SparseInst to your friends.
