### ISSUE TITLE
can release more model like cspdarknet-sparseinst

### ISSUE THREAD

**Issue by DDGRCF** [hustvl/SparseInst#91]

**Comment by wondervictor** [comment]
Hi @DDGRCF, thanks for your interest in SparseInst! We're planning to release these models in days~Please stay tuned ☕️

**Comment by DDGRCF** [comment]
> 
Thanks for your reply. And recently, I have released the [sparseinst deployment](https://github.com/DDGRCF/sparseinst_ncnn_demo) in ncnn.

**Comment by wondervictor** [comment]
Hi @DDGRCF, SparseInst with CSP-Darknet53 has been released!
